services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./client:/app
      - /app/node_modules
  storybook:
    container_name: storybook
    build:
      context: .
      dockerfile: Dockerfile.storybook
    ports:
      - "6006:6006"
    volumes:
      - "./client:/app"
      - "/app/node_modules"
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./server:/app
      - /app/node_modules
  db:
    container_name: postgresql
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "909:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  

volumes:
  pgdata:
  prometheus-data: